[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["cd server && npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = ["cd server && npx prisma generate"]

[start]
cmd = "cd server && npm start"
