[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install && npx prisma generate"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
