[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit --maxsockets=1"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npm start"
